syntax on
set background=dark
color gruvbox
set noshowmode
set t_Co=256
let g:lightline = {'colorscheme': 'gruvbox', }
set enc=utf-8
set ls=2
set incsearch
set hlsearch
set nu
set scrolloff=5
set nobackup
set nowritebackup
set noswapfile
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent
